"""Gera as páginas estáticas e materiais próprios a partir do conteúdo editorial."""
from pathlib import Path
import json,html,re
ROOT=Path(__file__).resolve().parents[1];DATA=json.loads((ROOT/'conteudo/curso.json').read_text());M=DATA['modules'];T=DATA['tracks'];VERSION=DATA['version'];E=html.escape
manifest={'course':{'id':'pilulasdeouro','title':DATA['title']},'tracks':[{'n':t['n'],'title':t['title'],'modules':[{'id':m['id'],'title':m['title'],'topics':len(m['topics']),'href':f'curso/trilha{t["n"]}/modulo-{m["id"]}.html'} for m in M if m['id'].startswith(str(t['n'])+'-')]} for t in T]}
ANTI="""(function(){try{var p=JSON.parse(localStorage.getItem('inema.prefs')||'{}'),d=document.documentElement;d.classList.toggle('dark',p.theme?p.theme!=='claro'&&p.theme!=='sepia':localStorage.getItem('theme')!=='light');if(['sepia','foco','contraste'].includes(p.theme))d.dataset.theme=p.theme;if(p.fontScale)d.style.fontSize=p.fontScale+'%';if(p.font)d.dataset.font=p.font;if(p.lineWidth)d.dataset.lineWidth=p.lineWidth;if(p.leading)d.dataset.leading=p.leading<=1.5?'compacto':'confortavel';if(p.accent)d.dataset.accent=p.accent}catch(e){document.documentElement.classList.add('dark')}})();"""
CONTRACT='''<!-- THESIS: Aprender uma técnica e sair com uma entrega verificável.
OWN-WORLD: INEMA v2 escolhido pelo usuário; escuro âmbar, trilhas emerald/blue/purple/amber, Inter, diagramas geométricos e superfícies de leitura.
STORY: escolher uma trilha, ler um módulo, praticar, conferir e retomar o estudo.
FIRST VIEWPORT: navegação completa, ferramentas de aprendizagem e título com orientação de uso; landing com mapa conceitual ao lado.
FORM: estrutura de curso e leitura fixada pelo formato v2; sem sorteio de linguagem visual.
FINISH: unreviewed and undocumented is unfinished; this build ends with the finish review, the verdict, and DESIGN.md -->'''
def meter(scope,label):return f'<div class="meter" data-inema-meter="{scope}" aria-label="{label}"><div class="meter-line"><span data-inema-meter-frac>0 de 0</span><span data-inema-meter-pct>0%</span></div><div class="meter-track"><div class="meter-fill" data-inema-meter-fill></div></div></div>'
def nav(root,active):
 links=''.join(f'<a class="track-{t["n"]}" href="{root}curso/trilha{t["n"]}/index.html" '+('aria-current="page"' if active==t['n'] else '')+f'><span class="long">{t["n"]}. {t["title"]}</span></a>' for t in T)
 return f'''<a class="skip" href="#conteudo">Pular para o conteúdo</a><nav class="site-nav" aria-label="Navegação do curso"><div class="wrap nav-inner"><div class="brand-group"><a class="brand" href="{root}index.html" aria-label="Pílulas de Ouro, início"><svg viewBox="0 0 32 32" aria-hidden="true"><path d="M16 2 29 10v12L16 30 3 22V10Z" fill="none" stroke="currentColor" stroke-width="2"/><path d="m10 12 6-4 6 4v8l-6 4-6-4Z" fill="currentColor"/></svg><span class="brand-name">Pílulas de Ouro</span></a><span class="muted" aria-hidden="true">|</span><a class="club text-sky-400" href="https://inema.club" target="_blank" rel="noopener">INEMA.CLUB</a></div><div class="nav-links">{links}</div><button class="theme-toggle js-only" id="theme-toggle" aria-label="Alternar tema claro e escuro"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><circle cx="12" cy="12" r="4"/><path d="M12 2v3m0 14v3M2 12h3m14 0h3M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2"/></svg></button></div></nav>'''
def appearance():
 groups=[('Tema','theme',[('inema-dark','Escuro'),('claro','Claro'),('sepia','Sépia'),('foco','Foco'),('contraste','Alto contraste')]),('Tamanho do texto','fontscale',[('100','Padrão'),('112','Maior'),('125','Grande')]),('Largura da leitura','linewidth',[('60','Estreita'),('68','Média'),('75','Ampla')]),('Entrelinha','leading',[('1.45','Compacta'),('1.7','Confortável')]),('Fonte','font',[('inter','Inter'),('system','Sistema')]),('Acento','accent',[('emerald','Verde'),('blue','Azul'),('purple','Roxo'),('amber','Âmbar')])]
 return '<div class="appearance" id="appearance" data-inema-appearance data-open="false" role="region" aria-label="Preferências de leitura">'+''.join('<div class="pref-group"><p>'+name+'</p><div class="pref-options">'+''.join(f'<button type="button" data-inema-set-{attr}="{v}" aria-pressed="false">{label}</button>' for v,label in opts)+'</div></div>' for name,attr,opts in groups)+'</div>'
def toolbar(root):return f'<div class="wrap toolbar js-only"><div class="tools"><button type="button" data-inema-journey-open>Minha jornada</button><button type="button" data-inema-appearance-toggle="#appearance" aria-controls="appearance" aria-expanded="false">Aparência</button><button type="button" data-continue="{root}curso/trilha1/modulo-1-1.html">Continuar estudo</button>{appearance()}</div>{meter("curso","Progresso do curso")}</div>'
def diagram(labels,uid,color,caption='Um caminho pequeno, com entrada e resultado verificáveis.'):
 def draw(mobile):
  width,height=(360,370) if mobile else (800,180);nodes=[];lines=[]
  for i,label in enumerate(labels):
   x,y=(55,12+i*90) if mobile else (12+i*200,46);w,h=(250,62) if mobile else (176,76)
   fill='#0e1b26' if i in (1,2) else '#171d2a';stroke='#38bdf8' if i in(1,2) else color
   nodes.append(f'<g><rect x="{x}" y="{y}" width="{w}" height="{h}" rx="12" fill="{fill}" stroke="{stroke}" stroke-width="2"'+(f' filter="url(#{uid}-{mobile}-glow)"' if i==3 else '')+f'/><text x="{x+w/2}" y="{y+23}" text-anchor="middle" fill="{stroke}" font-size="12">ETAPA {i+1}</text><text x="{x+w/2}" y="{y+47}" text-anchor="middle" fill="#e5e7eb" font-size="17" font-weight="600">{E(label)}</text></g>')
   if i<3:lines.append(f'<path d="M{x+w/2},{y+h} v28"/>' if mobile else f'<path d="M{x+w},{y+h/2} h24"/>')
  return f'<svg class="w-full h-auto {"mobile-diagram" if mobile else "desktop-diagram"}" viewBox="0 0 {width} {height}" role="img" aria-label="{E(" → ".join(labels))}" font-family="Inter,sans-serif"><defs><filter id="{uid}-{mobile}-glow"><feGaussianBlur stdDeviation="1.8" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter><pattern id="{uid}-{mobile}-grid" width="24" height="24" patternUnits="userSpaceOnUse"><circle cx="2" cy="2" r="1" fill="{color}" opacity=".13"/></pattern></defs><rect width="100%" height="100%" fill="url(#{uid}-{mobile}-grid)"/><g stroke="{color}" stroke-width="1.8" opacity=".6">{"".join(lines)}</g>{"".join(nodes)}</svg>'
 return f'<figure class="diagram">{draw(False)}{draw(True)}<figcaption>{E(caption)}</figcaption></figure>'
def shell(path,title,desc,body,active=0,extra=''):
 root='../'*len(Path(path).parts[:-1]);canonical='https://inematds.github.io/pilulasdeouro/'+('' if path=='index.html' else path)
 htmlpage=f'''<!DOCTYPE html><html lang="pt-BR" class="dark"><head><meta charset="utf-8"><script>{ANTI}</script><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="inema-course" content="pilulasdeouro"><meta name="inema-root" content="{root or './'}"><meta name="description" content="{E(desc)}"><meta name="theme-color" content="#111827"><title>{E(title)} | Pílulas de Ouro · INEMA</title><link rel="canonical" href="{canonical}"><meta property="og:title" content="{E(title)}"><meta property="og:description" content="{E(desc)}"><meta property="og:type" content="website"><link rel="icon" href="{root}assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="{root}assets/fonts.css"><link rel="stylesheet" href="{root}assets/learn.css"><link rel="stylesheet" href="{root}assets/site.css"><script type="application/json" data-inema-manifest>{json.dumps(manifest,ensure_ascii=False)}</script></head><body class="track-{active or 4}">{CONTRACT}{nav(root,active)}{toolbar(root)}<noscript><p class="noscript-note">O conteúdo está disponível para leitura. Ative JavaScript para salvar progresso e anotações.</p></noscript><main id="conteudo" class="wrap">{body}</main><footer class="footer"><div class="wrap"><span>Pílulas de Ouro · INEMA · v{VERSION}</span><span><a href="{root}materiais/index.html">Materiais do aluno</a> · <a href="{root}index.html">Início do curso</a></span></div></footer><script src="{root}assets/learn.js"></script><script src="{root}assets/site.js"></script>{extra}</body></html>'''
 out=ROOT/path;out.parent.mkdir(parents=True,exist_ok=True);out.write_text(htmlpage.replace('><','>\n<'))
def preview():return '<dialog class="preview" id="module-preview" aria-labelledby="preview-title"><div class="preview-bar"><strong id="preview-title">Prévia do módulo</strong><button class="button small" onclick="closeModal()">Fechar prévia</button></div><iframe title="Prévia do módulo"></iframe></dialog>'
def card(m):
 id=m['id'];num=id.replace('-','.');topics=''
 for i,t in enumerate(m['topics'],1):
  pid=f'{id}-resumo-{i}';topics+=f'<div class="topic-item"><button class="topic-toggle" type="button" onclick="toggleTopic(this)" aria-expanded="false" aria-controls="{pid}"><span class="number">{i}</span><span>{E(t["title"])}</span></button><div class="topic-explanation" id="{pid}"><p><strong>O que é</strong><br>{E(t["body"].split(". ")[0])}.</p><p><strong>Por que aprender</strong><br>{E(t["why"])}</p><p><strong>Conceitos-chave</strong><br>{E(" · ".join(k[0] for k in t["keys"]))}</p></div></div>'
 return f'<article class="module-card" id="modulo-{id}" data-inema-module="{id}" data-inema-track="{id[0]}"><div class="module-card-head"><div class="map-meta"><span>Módulo {num}</span><span>~35 min com prática</span></div><h3 class="text-2xl font-bold">{E(m["title"])}</h3><p>{E(m["description"])}</p>{meter("modulo:"+id,"Progresso do módulo "+num)}</div>{topics}<div class="actions justify-start"><a class="button primary" href="modulo-{id}.html">Ver Completo</a><button class="button js-only" onclick="openModal(\'modulo-{id}.html\', \'Módulo {num}\')">Ver em Modal</button></div></article>'
def codebox(code,id,label='Exemplo de trabalho'):
 return f'<div class="code-box"><div class="code-head"><span>{label}</span><button type="button" class="copy js-only" data-copy="{id}">Copiar</button></div><pre id="{id}"><code>{E(code)}</code></pre></div>'
def comparison(m,idx):return f'<div class="comparison"><div class="do"><h3>✓ Fazer</h3><p>{E(m["good"][idx])}</p></div><div class="avoid"><h3>✗ Evitar</h3><p>{E(m["bad"][idx])}</p></div></div>'
for t in T:
 modules=[m for m in M if m['id'].startswith(str(t['n'])+'-')]
 body=f'<div class="breadcrumb"><a href="../../index.html">Início</a> / Trilha {t["n"]}</div><header class="page-head"><p class="badge">TRILHA {t["n"]}</p><h1>{t["emoji"]} {t["title"]}</h1><p>{t["description"]}</p><div class="page-stats"><div><strong>3 módulos</strong><span>Um passo de cada vez</span></div><div><strong>18 tópicos</strong><span>Leitura com anotações</span></div><div><strong>~1h45</strong><span>Estimativa com práticas</span></div><div><strong>Aplicação prática</strong><span>Exemplos comentados</span></div></div></header>'
 body+=diagram(['Entender','Aplicar','Conferir','Entregar'],f't{t["n"]}',t['hex'],t['subtitle'])
 body+='<h2>Mapa da trilha</h2><div class="map-grid">'+''.join(f'<a class="map-card" href="#modulo-{m["id"]}"><div class="map-meta"><span>{m["id"].replace("-",".")}</span><span>~35 min</span></div><h3>{t["emoji"]} {E(m["title"])}</h3><p>{["Uma saída que faz sentido.","Menos suposição. Mais evidência.","Pratique e feche a etapa."][i]}</p></a>' for i,m in enumerate(modules))+'</div><h2 class="text-2xl font-bold">Conteúdo detalhado</h2>'
 body+=''.join(card(m) for m in modules)+preview();shell(f'curso/trilha{t["n"]}/index.html',t['title'],t['description'],body,t['n'])
for mi,m in enumerate(M):
 id=m['id'];tk=int(id[0]);t=T[tk-1];body=f'<div class="breadcrumb"><a href="../../index.html">Início</a> / <a href="index.html">{t["title"]}</a> / Módulo {id.replace("-",".")}</div><header class="page-head"><p class="badge">MÓDULO {id.replace("-",".")}</p><h1>{E(m["title"])}</h1><p>{E(m["description"])}</p><div class="page-stats"><div><strong>6 tópicos</strong><span>Conceitos e aplicação</span></div><div><strong>~35 minutos</strong><span>Estimativa com prática</span></div><div><strong>Prático</strong><span>Passo a passo</span></div><div><strong>Sua entrega</strong><span>{E(m["outcome"])}</span></div></div></header>'
 body+=diagram(m['flow'],'m'+id,t['hex'],m['outcome'])
 body+='<div class="lesson-layout"><nav class="lesson-toc" data-inema-toc aria-label="Índice do módulo"><strong>Neste módulo</strong><ul>'+''.join(f'<li><a class="inema-toc-link" href="#topico-{i}">{i}. {E(top["title"])}</a></li>' for i,top in enumerate(m['topics'],1))+'</ul>'+meter('modulo:'+id,'Progresso deste módulo')+'</nav>'+f'<article class="lesson" id="modulo-{id}" data-inema-module="{id}" data-inema-track="{tk}">'
 for i,top in enumerate(m['topics'],1):
  body+=f'<section class="topic-section" id="topico-{i}" data-inema-topic="modulo-{id}#topico-{i}"><div class="topic-heading"><span class="number large">{i}</span><h2>{E(top["title"])}</h2></div><div class="inema-prose">'
  body+=''.join(f'<p data-inema-block="m{id}-t{i}-p{j}">{E(p)}</p>' for j,p in enumerate(top['body'].split('\n\n'),1))+'</div>'
  body+=f'<div class="why"><h3>Por que aprender</h3><p data-inema-block="m{id}-t{i}-p3">{E(top["why"])}</p></div>'
  if i in (1,4):body+=comparison(m,0 if i==1 else 1)
  if i==2:body+='<h3>Um caminho para aplicar</h3><ol class="timeline">'+''.join(f'<li>{E(step)}</li>' for step in m['steps'])+'</ol>'
  if i==3:body+=codebox(m['example'],f'exemplo-{id}')+f'<aside class="tip"><strong>Dica prática</strong>{E(m["good"][0])} Registre o resultado antes de mudar outra parte do processo.</aside>'
  if i==5:body+='<div class="table-wrap"><table><caption>Critérios para conferir sua entrega</caption><thead><tr><th scope="col">Critério</th><th scope="col">Evidência esperada</th></tr></thead><tbody>'+''.join(f'<tr><th scope="row">{E(a)}</th><td>{E(b)}</td></tr>' for a,b in m['criteria'])+'</tbody></table></div>'+f'<aside class="tip"><strong>Antes de avançar</strong>{E(m["good"][1])} Se algum critério falhar, descreva o caso e ajuste essa parte.</aside>'
  if i==6:
   body+=f'<div class="practice"><h3>Seu exercício</h3><p>{E(m["exercise"])}</p><a class="button small" href="../../materiais/pratica-{id}.md" download>Baixar ficha da prática</a></div><details class="solution"><summary>Conferir resposta comentada</summary><pre>{E(m["solution"])}</pre></details><div class="check" data-inema-check="modulo-{id}#q1"><h3>Cheque sua compreensão</h3><p>{E(m["question"])}</p><div class="check-options">'+''.join(f'<button type="button" class="js-only" data-inema-check-option="{j}">{E(opt)}</button>' for j,opt in enumerate(m['options']))+f'</div><div data-inema-check-feedback role="status" aria-live="polite"></div><noscript><p>{E(m["options"][m["answer"]])} {E(m["explanation"])}</p></noscript></div>'
  body+='<h3>Conceitos-chave</h3><div class="concepts">'+''.join(f'<div><strong>{E(a)}</strong><span>{E(b)}</span></div>' for a,b in top['keys'])+'</div>'
  body+='<div class="read-controls js-only justify-start"><button type="button" data-inema-read-toggle aria-pressed="false"><span class="inema-read-icon" aria-hidden="true">○</span><span class="inema-read-label">Marcar como lido</span></button><button type="button" data-inema-doubt-toggle aria-pressed="false">Tenho dúvida</button></div></section>'
 body+=f'<section class="module-outcome"><h2>O que fica deste módulo</h2><p>{E(m["outcome"])}</p><ul>'+''.join(f'<li>✓ {E(c[1])}</li>' for c in m['criteria'])+'</ul><p class="public-notice">O progresso registra sua leitura. A prática fica concluída quando você confere a entrega.</p><div class="actions justify-start"><a class="button" href="index.html">Voltar para a trilha</a>'
 if mi+1<len(M):
  nxt=M[mi+1];body+=f'<a class="button primary" href="../trilha{nxt["id"][0]}/modulo-{nxt["id"]}.html">Próximo módulo: {E(nxt["title"])}</a>'
 else:body+='<a class="button primary" href="../../materiais/index.html">Reunir minhas entregas</a>'
 body+='</div></section></article></div>'
 q={'id':f'modulo-{id}#q1','q':m['question'],'options':m['options'],'answer':str(m['answer']),'explain':{str(j):m['explanation'] for j in range(len(m['options']))}}
 shell(f'curso/trilha{tk}/modulo-{id}.html',m['title'],m['description'],body,tk,f'<script type="application/json" data-quiz-definition>{json.dumps(q,ensure_ascii=False)}</script>')
 (ROOT/f'materiais/pratica-{id}.md').write_text(f'# Prática {id.replace("-",".")} — {m["title"]}\n\n## Entrega\n\n{m["outcome"]}\n\n## Exercício\n\n{m["exercise"]}\n\n## Critérios\n\n'+''.join(f'- [ ] {b}\n' for a,b in m['criteria'])+'\n## Meu resultado\n\nArquivo entregue:\n\nVerificação realizada:\n\nPendência ou próximo passo:\n')
body=f'<section class="hero"><div><h1>Pílulas<br>de <span class="gold">Ouro.</span></h1><p class="subtitle">IA em projetos práticos.</p><p class="intro">Aprenda a transformar um pedido em uma entrega que funciona. Uma técnica por vez, com exemplos, prática e um jeito claro de conferir o resultado.</p><div class="actions"><a class="button primary" href="curso/trilha1/modulo-1-1.html">Começar pela primeira prática</a><a class="button" href="#trilhas">Explorar as trilhas</a></div></div><div class="hero-lab"><p class="lab-heading">Da ideia à entrega <span>UM PASSO DE CADA VEZ</span></p>{diagram(["Delimitar","Produzir","Conferir","Entregar"],"hero","#fbbf24","O método acompanha você do primeiro pedido ao projeto final.")}<p class="lab-output"><strong>Seu ponto de chegada:</strong> uma central de pedidos e um kit de entrega que outra pessoa consegue usar.</p></div></section><div class="course-facts"><span><strong>4</strong> trilhas</span><span><strong>12</strong> módulos</span><span><strong>72</strong> tópicos</span><span><strong>12</strong> práticas</span><span><strong>~7h</strong> com exercícios</span></div>'
body+='<section class="section-space" id="trilhas"><div class="section-heading"><h2>Escolha seu próximo passo</h2><p>Comece pelos fundamentos ou retome o assunto de que seu projeto precisa.</p></div><div class="track-list">'+''.join(f'<a class="track-row track-{t["n"]}" href="curso/trilha{t["n"]}/index.html"><span class="track-number">0{t["n"]}</span><div><h3>{t["title"]}</h3><p class="tagline">{t["subtitle"]}</p></div><p class="track-desc">{t["description"]}</p><span class="start-label">Abrir trilha</span></a>' for t in T)+'</div></section>'
body+='<section class="two-col"><div class="panel"><h2>Estude com o seu projeto em mente</h2><p>Você precisa apenas de um navegador e familiaridade básica com arquivos. As práticas de código podem ser feitas com um assistente de programação.</p><p>Os exemplos usam dados fictícios. Ferramentas externas são opcionais nas atividades conceituais e podem exigir conta ou configuração própria.</p></div><div class="panel"><h2>Seu espaço de aprendizagem</h2><ul><li>Marque os tópicos lidos e aqueles que geraram dúvida.</li><li>Selecione um trecho para grifar ou anotar.</li><li>Retome pelo botão “Continuar estudo”.</li><li>Exporte sua jornada para guardar uma cópia ou mudar de navegador.</li></ul><p class="public-notice">Progresso e notas ficam neste navegador. Exporte pela Minha jornada para ter uma cópia.</p></div></section><section class="section-space"><h2>Termine com algo que pode mostrar</h2><div class="two-col"><article class="panel"><h3>Central de pedidos</h3><p>Importe dados, preserve pendências, trate duplicatas e exporte uma tabela conferida.</p><a href="curso/trilha4/modulo-4-2.html">Conhecer o primeiro projeto</a></article><article class="panel"><h3>Kit de entrega e conhecimento</h3><p>Reúna instruções, mapa do fluxo, exemplos e evidências para continuar o trabalho com clareza.</p><a href="curso/trilha4/modulo-4-3.html">Conhecer o projeto de conclusão</a></article></div></section>'
shell('index.html','Pílulas de Ouro — IA em projetos práticos','Curso prático de IA com quatro trilhas, doze módulos, exercícios e projetos verificáveis.',body)
materials='<header class="page-head"><h1>Materiais do aluno</h1><p>Baixe as fichas em Markdown, preencha os resultados e mantenha suas evidências de prática.</p></header><div class="table-wrap"><table><thead><tr><th>Módulo</th><th>Ficha de prática</th></tr></thead><tbody>'+''.join(f'<tr><td>{m["id"].replace("-",".")}</td><td><a href="pratica-{m["id"]}.md" download>{E(m["title"])}</a></td></tr>' for m in M)+'</tbody></table></div><div class="actions"><a class="button primary" href="curso-completo.md" download>Baixar curso em Markdown</a><a class="button" href="entrada-pedidos.csv" download>Baixar pedidos fictícios em CSV</a><a class="button" href="../PLANO-PROJETOS.md">Plano de projetos</a></div><section class="section-space"><h2>Como guardar o seu trabalho</h2><p>Use uma pasta para cada prática. Guarde a entrada, a saída e a conferência. As fichas não são enviadas para nenhum servidor.</p><p>As anotações feitas nas páginas são exportadas separadamente pelo painel Minha jornada.</p></section>'
shell('materiais/index.html','Materiais do aluno','Fichas práticas, dados fictícios e versão de leitura do curso.',materials)
(ROOT/'materiais/entrada-pedidos.csv').write_text('id,cliente,tarefa,prazo\nP-01,Oficina fictícia Norte,Revisar catálogo,2026-11-02\nP-02,Ateliê fictício Lua,Organizar imagens,\nP-01,Oficina fictícia Norte,Revisar catálogo,2026-11-02\n')
full=['# Pílulas de Ouro — IA em projetos práticos','',f'INEMA · versão {VERSION}','']
for m in M:
 full+=['## '+m['id'].replace('-','.')+' · '+m['title'],'',m['description'],'','Entrega: '+m['outcome'],'']
 for i,top in enumerate(m['topics'],1):full+=['### '+str(i)+'. '+top['title'],'',top['body'],'','**Por que aprender:** '+top['why'],'','**Conceitos-chave:** '+ '; '.join(a+': '+b for a,b in top['keys']), '']
 full+=['### Prática','',m['exercise'],'','### Resposta comentada','',m['solution'],'','### Exemplo','', '```text',m['example'],'```','']
(ROOT/'materiais/curso-completo.md').write_text('\n'.join(full))
(ROOT/'assets/favicon.svg').write_text('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" rx="8" fill="#111827"/><path d="m16 4 11 7v10l-11 7L5 21V11Z" fill="none" stroke="#facc15" stroke-width="2"/><path d="m11 12 5-3 5 3v8l-5 3-5-3Z" fill="#facc15"/></svg>')
(ROOT/'.nojekyll').touch()
print('Geradas',len(list((ROOT/'curso').rglob('*.html')))+2,'páginas e 12 fichas práticas.')
